import fs from 'node:fs'
import sql from 'mssql'
import { createClient, type Client } from '@libsql/client'
import { serverConfig } from '../config.js'
import type { DbAdapter } from './adapter.js'
import { LibsqlAdapter } from './adapters/libsql-adapter.js'
import { MssqlAdapter } from './adapters/mssql-adapter.js'

let adapter: DbAdapter | null = null
let rawClient: Client | null = null
let sqlPool: sql.ConnectionPool | null = null

export const getDbAsync = async (): Promise<DbAdapter> => {
  if (adapter) return adapter

  const mode = serverConfig.db.mode

  if (mode === 'sqlserver') {
    const { server, port, database, user, password } = serverConfig.db
    if (!server || !database) throw new Error('DB_MODE is "sqlserver" but DB_SERVER/DB_DATABASE are not configured.')
    sqlPool = await sql.connect({
      server,
      port,
      database,
      user,
      password,
      options: { encrypt: true, trustServerCertificate: false },
      pool: { max: 10, min: 0, idleTimeoutMillis: 30000 },
    })
    console.log('Database: connected to SQL Server')
    adapter = new MssqlAdapter(sqlPool)
    return adapter
  }

  // turso or sqlite (local)
  const tursoUrl = serverConfig.db.tursoUrl.trim()
  if (tursoUrl) {
    rawClient = createClient({ url: tursoUrl, authToken: serverConfig.db.tursoToken.trim() || undefined })
    console.log('Database: connected to Turso remote')
  } else {
    const sqlitePath = serverConfig.db.sqlitePath || './data.db'
    rawClient = createClient({ url: `file:${sqlitePath}` })
    console.log(`Database: connected to local SQLite (${sqlitePath})`)
  }
  adapter = new LibsqlAdapter(rawClient)
  return adapter
}

// Synchronous getDb for backward compat — returns raw libsql client
// For sqlserver mode, returns an in-memory stub (callers should use getDbAsync instead)
export const getDb = (): Client => {
  if (rawClient) return rawClient
  const mode = serverConfig.db.mode
  if (mode === 'sqlserver') {
    if (!rawClient) rawClient = createClient({ url: 'file::memory:' })
    return rawClient
  }
  // Lazy init for turso/sqlite
  const tursoUrl = serverConfig.db.tursoUrl.trim()
  if (tursoUrl) {
    rawClient = createClient({ url: tursoUrl, authToken: serverConfig.db.tursoToken.trim() || undefined })
  } else {
    const sqlitePath = serverConfig.db.sqlitePath || './data.db'
    rawClient = createClient({ url: `file:${sqlitePath}` })
  }
  return rawClient
}

export const getPool = async (): Promise<sql.ConnectionPool> => {
  if (sqlPool) return sqlPool
  await getDbAsync()
  if (!sqlPool) throw new Error('Failed to create SQL Server pool')
  return sqlPool
}

export const closeDb = async (): Promise<void> => {
  if (adapter) {
    await adapter.close()
    adapter = null
  }
  if (rawClient) {
    rawClient.close()
    rawClient = null
  }
  if (sqlPool) {
    await sqlPool.close()
    sqlPool = null
  }
}

/**
 * Run a SQL Server seed file (generated by migrate-turso-to-sqlserver.mjs).
 * Handles IDENTITY_INSERT batch merging for mssql's sp_reset_connection behavior.
 */
export const runSqlServerSeedFile = async (seedPath: string): Promise<void> => {
  if (!fs.existsSync(seedPath)) {
    console.warn(`[db] Seed file not found: ${seedPath}`)
    return
  }

  const content = fs.readFileSync(seedPath, 'utf8')
  // Split by GO statements or semicolons
  const batches = content
    .split(/^\s*GO\s*$/im)
    .flatMap((chunk) => chunk.split(';'))
    .map((s) => s.trim())
    .filter((s) => s.length > 0)

  const pool = await getPool()

  // Merge IDENTITY_INSERT ON batches with following INSERT batches
  const mergedBatches: string[] = []
  for (let i = 0; i < batches.length; i++) {
    const batch = batches[i]
    if (/SET\s+IDENTITY_INSERT\s+\S+\s+ON/i.test(batch) && i + 1 < batches.length) {
      mergedBatches.push(`${batch}; ${batches[i + 1]}`)
      i++ // skip next batch as it's merged
    } else if (/SET\s+IDENTITY_INSERT\s+\S+\s+OFF/i.test(batch)) {
      // Append OFF to previous batch if exists
      if (mergedBatches.length > 0) {
        mergedBatches[mergedBatches.length - 1] += `; ${batch}`
      } else {
        mergedBatches.push(batch)
      }
    } else {
      mergedBatches.push(batch)
    }
  }

  console.log(`[db] Running seed file: ${seedPath} (${mergedBatches.length} batches)`)

  for (const batch of mergedBatches) {
    try {
      await pool.request().query(batch)
    } catch (err) {
      // Log but continue — seed file uses TRY/CATCH for duplicates
      const msg = err instanceof Error ? err.message : String(err)
      if (!msg.includes('already exists') && !msg.includes('duplicate')) {
        console.warn(`[db] Seed batch warning: ${msg.substring(0, 200)}`)
      }
    }
  }

  console.log('[db] Seed file complete')
}
